export const APP_THEME = {
  screenBackground: "#f5f5f5",
  textPrimary: "#18181b",
  textMuted: "#71717a",
  cardBackground: "#ffffff",
  buttonBackground: "#e02e24",
  buttonText: "#ffffff",
  link: "#2563eb",
  error: "#b91c1c",
  border: "#e4e4e7",
  cardBorder: "#ebebeb",
  updateIndicator: "#22c55e",
  accent: "#e02e24",
  headerBackground: "#ffffff",
  tabBarBackground: "#ffffff",
  tabInactive: "#71717a",
  tabActive: "#e02e24",
  overlay: "rgba(0, 0, 0, 0.35)",
  searchBackground: "#ededed",
} as const;
